name: Trigger CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

  push-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Create ZIP archive
        run: zip -r cdapp.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Push to S3 Bucket
        run: aws s3 cp ./cdapp.zip s3://codedeploy-bucket-jabriel/cdapp.zip
  
  trigger-codedeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Create CodeDeploy Deployment
      run: |
       aws deploy create-deployment \
        --application-name test-code-deploy \
        --deployment-group-name cd-bluegreen \
        --s3-location bucket=codedeploy-bucket-jabriel,key=cdapp.zip,bundleType=zip